export const GET_RANDOM_WORD_LOADING = "GET_RANDOM_WORD_LOADING";
export const GET_RANDOM_WORD_SUCCESS = "GET_RANDOM_WORD_SUCCESS";
export const GET_RANDOM_WORD_ERROR = "GET_RANDOM_WORD_ERROR";
export const POST_SCORE = "POST_SCORE";
export const GET_SCORE = "GET_SCORE";
export const CHANGE_SCORE = "CHANGE_SCORE";
